// [CustomSTT] Built-in radiology vocabulary for STT keyterm backfill.
// Terms ranked by transcription difficulty (hardest first).
// Sources: Radiopaedia, Fleischner Society, PMC studies on STT errors in radiology.
namespace MosaicTools.Services;

/// <summary>
/// ~1000 radiology terms ranked by transcription difficulty for STT keyterm boosting.
/// Used as backfill after manual and auto-learned terms to fill provider capacity.
/// </summary>
public static class RadiologyKeyterms
{
    /// <summary>
    /// Terms sorted hardest-to-transcribe first: confused pairs, multi-syllabic Latin/Greek,
    /// eponyms, contrast agents, procedures, imaging descriptors, common pathology.
    /// </summary>
    public static readonly string[] Terms =
    {
        // === COMMONLY CONFUSED PAIRS (highest clinical danger) ===
        "ileum", "ilium",
        "perineal", "peroneal",
        "peritoneal",
        "humeral", "humoral",
        "metacarpal", "metatarsal",
        "malleolus", "malleus",
        "iliac", "ileac",
        "celiac",
        "sellar",
        "fascial", "facial", "faucial",
        "falx",
        "carotid", "parotid",
        "glands", "glans",
        "osteal", "ostial",
        "viscous", "viscus",
        "dysphasia", "dysphagia",
        "mucous", "mucus",
        "cirrhosis", "xerosis",
        "scotoma",
        "miosis", "mitosis",
        "mycosis", "myiasis",
        "melanotic", "melenic",
        "metaphysis", "metastasis",
        "apophysis", "epiphysis",
        "diaphysis", "diathesis", "diastasis",
        "infarction", "infraction", "infection",
        "effusion", "infusion", "affusion",
        "perfusion", "profusion",
        "instillation",
        "denervation", "innervation", "enervation",
        "callous", "callus",
        "discreet", "discrete",
        "palpable", "palpebral",
        "palpation", "palpitation",
        "labial", "labile",
        "pleural", "plural",
        "myoclonic", "myotonic",
        "bolus", "bullous",
        "radical", "radicle",
        "prostate", "prostrate",
        "creatine", "creatinine",
        "anuresis", "enuresis",
        "menorrhagia", "metrorrhagia",
        "venous",
        "abduction", "adduction",
        "afferent", "efferent",
        "evert", "invert",

        // === TIER 1 ANATOMY (6+ syllables, extremely difficult) ===
        "pneumomediastinum",
        "choledocholithiasis",
        "spondylolisthesis",
        "spondyloarthropathy",
        "chondromalacia",
        "osteochondritis",
        "osteoarthropathy",
        "encephalomyelitis",
        "meningoencephalitis",
        "leukoencephalopathy",
        "pachymeningitis",
        "periventricular",
        "juxtacortical",
        "retropharyngeal",
        "glossopharyngeal",
        "pterygopalatine",
        "sphenopalatine",
        "infundibulum",
        "cholecystolithiasis",
        "hepatosplenomegaly",
        "pancreaticoduodenal",
        "gastroesophageal",
        "esophagogastric",
        "duodenojejunal",
        "ureteropelvic",
        "vesicoureteral",
        "acromioclavicular",
        "sternoclavicular",
        "sacroiliac",
        "iliopsoas",
        "gastrocnemius",
        "sternocleidomastoid",
        "brachiocephalic",
        "femoroacetabular",

        // === TIER 1 PATHOLOGY (extremely difficult) ===
        "lymphadenopathy",
        "pneumoperitoneum",
        "cholangiocarcinoma",
        "hepatocellular",
        "hemochromatosis",
        "rhabdomyolysis",
        "pheochromocytoma",
        "craniopharyngioma",
        "oligodendroglioma",
        "schwannomatosis",
        "neurofibromatosis",
        "lymphangioleiomyomatosis",
        "pneumocystis",
        "coccidioidomycosis",
        "histoplasmosis",
        "aspergillosis",
        "mucormycosis",
        "sarcoidosis",
        "amyloidosis",
        "hemosiderosis",
        "pneumoconiosis",
        "bronchopneumonia",
        "bronchiectasis",
        "atelectasis",
        "pneumothorax",
        "hemothorax",
        "hydropneumothorax",
        "chylothorax",
        "empyema",
        "mesothelioma",
        "arteriovenous malformation",
        "pseudoaneurysm",
        "thromboembolism",
        "atherosclerosis",
        "arteriosclerosis",
        "lymphangitic carcinomatosis",
        "desquamative interstitial pneumonia",
        "cryptogenic organizing pneumonia",
        "hypersensitivity pneumonitis",

        // === EPONYMS (names garbled by STT) ===
        "Hounsfield",
        "Virchow-Robin",
        "Meckel",
        "Adamkiewicz",
        "Sylvian",
        "Rolandic",
        "Eustachian",
        "Fallopian",
        "Couinaud",
        "Calot",
        "Gerota",
        "Denonvilliers",
        "Waldeyer",
        "Treitz",
        "Santorini",
        "Wirsung",
        "Oddi",
        "Vater",
        "Glisson",
        "Batson",
        "Schmorl",
        "Fleischner",
        "Kerley",
        "Hampton",
        "Westermark",
        "Rigler",
        "Chilaiditi",
        "Boerhaave",
        "Budd-Chiari",
        "Hashimoto",
        "Graves",
        "Paget",
        "Hodgkin",
        "Ewing",
        "Wilms",
        "Klatskin",
        "Pancoast",
        "Krukenberg",
        "Joubert",
        "Dandy-Walker",
        "Arnold-Chiari",
        "Marfan",
        "Ehlers-Danlos",
        "Takayasu",
        "Kawasaki",
        "Behcet",
        "Raynaud",
        "Perthes",
        "Osgood-Schlatter",
        "Legg-Calve-Perthes",
        "Salter-Harris",
        "Lauge-Hansen",
        "Le Fort",
        "Colles",
        "Bennett",
        "Rolando",
        "Monteggia",
        "Galeazzi",
        "Maisonneuve",
        "Lisfranc",
        "Segond",
        "Hill-Sachs",
        "Bankart",
        "Bosniak",
        "Creutzfeldt-Jakob",
        "Guillain-Barre",
        "Rathke",

        // === CONTRAST AGENTS & RADIOPHARMACEUTICALS ===
        "gadolinium",
        "gadobutrol",
        "gadopentetate",
        "gadobenate",
        "gadoteridol",
        "gadodiamide",
        "gadoversetamide",
        "gadoterate",
        "gadoxetate",
        "gadopiclenol",
        "iopamidol",
        "iohexol",
        "iodixanol",
        "iopromide",
        "ioversol",
        "ioxilan",
        "diatrizoate",
        "iomeprol",
        "technetium",
        "fluorodeoxyglucose",
        "florbetapir",
        "flutemetamol",
        "fluciclovine",
        "dotatate",
        "sestamibi",
        "tetrofosmin",
        "pertechnetate",
        "mebrofenin",
        "pentetreotide",
        "methylenediphosphonate",
        "hydroxymethylene diphosphonate",
        "dimercaptosuccinic acid",
        "diethylenetriamine pentaacetic acid",
        "mercaptoacetyltriglycine",
        "dipyridamole",
        "regadenoson",
        "adenosine",
        "glucagon",
        "midazolam",
        "fentanyl",
        "lidocaine",
        "bupivacaine",
        "epinephrine",
        "methylprednisolone",
        "diphenhydramine",
        "acetylcysteine",
        "metformin",

        // === PROCEDURES (tier 1, extremely difficult) ===
        "cholecystectomy",
        "choledochojejunostomy",
        "esophagogastroduodenoscopy",
        "percutaneous transhepatic cholangiography",
        "vertebroplasty",
        "kyphoplasty",
        "discectomy",
        "laminectomy",
        "foraminotomy",
        "rhizotomy",
        "craniotomy",
        "ventriculoperitoneal",
        "thoracentesis",
        "paracentesis",
        "amniocentesis",
        "arthrocentesis",
        "pericardiocentesis",
        "angioplasty",
        "atherectomy",
        "thrombectomy",
        "embolectomy",
        "endarterectomy",
        "nephrectomy",
        "nephrostomy",
        "cholecystostomy",
        "tracheostomy",
        "gastrostomy",
        "jejunostomy",
        "cystoscopy",
        "colonoscopy",
        "bronchoscopy",
        "laparoscopy",
        "thoracoscopy",
        "mediastinoscopy",
        "arthroscopy",
        "hysteroscopy",
        "sigmoidoscopy",
        "fluoroscopy",
        "venography",
        "arthrography",
        "myelography",
        "sialography",
        "dacryocystography",
        "fistulography",
        "cystourethrography",
        "hysterosalpingography",
        "lithotripsy",
        "radiofrequency ablation",
        "cryoablation",
        "sclerotherapy",
        "sphincterotomy",
        "splenectomy",
        "thyroidectomy",
        "embolization",
        "thrombolysis",

        // === TIER 2 ANATOMY (4-6 syllables) ===
        "acetabulum",
        "acromion",
        "calcaneus",
        "capitellum",
        "claustrum",
        "coccyx",
        "cricoarytenoid",
        "cribriform",
        "diaphragm",
        "duodenum",
        "epididymis",
        "epiglottis",
        "ethmoid",
        "foramina",
        "glenohumeral",
        "hypothalamus",
        "jejunum",
        "ligamentum",
        "mesentery",
        "mesocolon",
        "nasopharynx",
        "oropharynx",
        "pericardium",
        "perichondrium",
        "periosteum",
        "peritoneum",
        "pituitary",
        "quadratus",
        "rectosigmoid",
        "retroperitoneum",
        "scapholunate",
        "sphincter",
        "supracondylar",
        "supraspinatus",
        "infraspinatus",
        "subscapularis",
        "teres",
        "trochanter",
        "trochlea",
        "tuberosity",
        "xiphoid",
        "zygapophyseal",
        "zygomatic",

        // === TIER 2 PATHOLOGY ===
        "achalasia",
        "adenocarcinoma",
        "adenoma",
        "aneurysm",
        "angiosarcoma",
        "ankylosis",
        "arachnoiditis",
        "arrhythmia",
        "astrocytoma",
        "cholelithiasis",
        "cholecystitis",
        "cholangitis",
        "chondrosarcoma",
        "coagulopathy",
        "dermatomyositis",
        "diverticulosis",
        "diverticulitis",
        "dysplasia",
        "ependymoma",
        "fibroadenoma",
        "fibrosarcoma",
        "glomerulonephritis",
        "glioblastoma",
        "granulomatosis",
        "hemarthrosis",
        "hematoma",
        "hydrocephalus",
        "hydronephrosis",
        "hyperplasia",
        "hypertrophy",
        "intussusception",
        "ischemia",
        "leiomyoma",
        "leiomyosarcoma",
        "lipomatosis",
        "lymphoma",
        "myelofibrosis",
        "myeloma",
        "nephrosclerosis",
        "osteomyelitis",
        "osteonecrosis",
        "osteophyte",
        "osteosarcoma",
        "pancreatitis",
        "papilloma",
        "pericarditis",
        "peritonitis",
        "phlegmon",
        "pneumatosis",
        "pneumobilia",
        "pseudomembranous",
        "pyelonephritis",
        "scoliosis",
        "spondylosis",
        "stenosis",
        "synovitis",
        "thrombocytopenia",
        "thrombus",
        "vasculitis",
        "volvulus",
        "meningioma",
        "thymoma",
        "teratoma",
        "hamartoma",
        "hemangioma",
        "lymphangioma",

        // === MRI/CT ABBREVIATIONS & SEQUENCES ===
        "FLAIR",
        "STIR",
        "DWI",
        "ADC",
        "SWI",
        "GRE",
        "FSE",
        "TSE",
        "EPI",
        "HASTE",
        "FIESTA",
        "CISS",
        "SPACE",
        "VIBE",
        "BLADE",
        "PROPELLER",
        "MRA",
        "MRV",
        "MRCP",
        "DTI",
        "PWI",
        "ASL",
        "TOF",
        "TRICKS",
        "Dixon",
        "IDEAL",
        "LAVA",
        "CTA",
        "CTV",
        "CTPA",
        "HRCT",
        "DECT",
        "NCCT",
        "MPR",
        "MIP",
        "MinIP",
        "VRT",
        "BI-RADS",
        "LI-RADS",
        "PI-RADS",
        "TI-RADS",
        "RECIST",
        "ASPECTS",
        "TNM",
        "SLAP",

        // === IMAGING DESCRIPTORS ===
        "hyperintense",
        "hypointense",
        "hyperattenuating",
        "hypoattenuating",
        "hyperdense",
        "hypodense",
        "hyperechoic",
        "hypoechoic",
        "anechoic",
        "isoechoic",
        "isointense",
        "isodense",
        "heterogeneous",
        "homogeneous",
        "echogenic",
        "echogenicity",
        "radiolucent",
        "radiopaque",
        "circumscribed",
        "spiculated",
        "lobulated",
        "pedunculated",
        "sessile",
        "infiltrative",
        "exophytic",
        "endophytic",
        "intraluminal",
        "extraluminal",
        "intraparenchymal",
        "extraparenchymal",
        "subpleural",
        "subependymal",
        "perivascular",
        "perihilar",
        "peribronchial",
        "centrilobular",
        "panlobular",
        "paraseptal",
        "interlobular",
        "intralobular",
        "reticulonodular",
        "ground-glass",
        "tree-in-bud",
        "crazy-paving",
        "mosaic attenuation",
        "air bronchograms",
        "air-fluid level",
        "meniscus sign",
        "crescent sign",
        "halo sign",
        "reverse halo sign",

        // === NEURORADIOLOGY ===
        "hippocampus",
        "amygdala",
        "caudate nucleus",
        "putamen",
        "globus pallidus",
        "thalamus",
        "subthalamic nucleus",
        "substantia nigra",
        "dentate nucleus",
        "cerebellar vermis",
        "cerebellar tonsil",
        "cerebral peduncle",
        "cerebellopontine angle",
        "choroid plexus",
        "optic chiasm",
        "corpus callosum",
        "cingulate gyrus",
        "precuneus",
        "insula",
        "supramarginal gyrus",
        "angular gyrus",
        "parahippocampal gyrus",
        "lentiform nucleus",
        "internal capsule",
        "corona radiata",
        "centrum semiovale",
        "glioblastoma multiforme",
        "medulloblastoma",
        "pineoblastoma",
        "pineocytoma",
        "hemangioblastoma",
        "vestibular schwannoma",
        "neurocysticercosis",
        "toxoplasmosis",
        "osmotic demyelination syndrome",
        "Wernicke encephalopathy",
        "amyotrophic lateral sclerosis",
        "holoprosencephaly",
        "schizencephaly",
        "lissencephaly",
        "polymicrogyria",
        "heterotopia",

        // === ABDOMINAL/GI ===
        "hepatic steatosis",
        "focal nodular hyperplasia",
        "hepatic adenoma",
        "ampullary carcinoma",
        "pancreatic pseudocyst",
        "intraductal papillary mucinous neoplasm",
        "mucinous cystic neoplasm",
        "serous cystadenoma",
        "solid pseudopapillary neoplasm",
        "omental caking",
        "peritoneal carcinomatosis",
        "ascites",
        "pneumatosis intestinalis",
        "sigmoid volvulus",
        "cecal volvulus",
        "appendicitis",
        "ulcerative colitis",
        "ischemic colitis",
        "pseudomembranous colitis",
        "epiploic appendagitis",
        "omental infarction",
        "mesenteric ischemia",
        "superior mesenteric artery",
        "inferior mesenteric artery",
        "celiac axis",
        "splenic artery aneurysm",
        "renal artery stenosis",
        "abdominal aortic aneurysm",
        "retroperitoneal fibrosis",
        "retroperitoneal lymphadenopathy",

        // === MUSCULOSKELETAL ===
        "spondylolysis",
        "retrolisthesis",
        "anterolisthesis",
        "annulus fibrosus",
        "nucleus pulposus",
        "disc herniation",
        "disc protrusion",
        "disc extrusion",
        "disc sequestration",
        "disc desiccation",
        "foraminal stenosis",
        "central canal stenosis",
        "lateral recess stenosis",
        "ligamentum flavum",
        "posterior longitudinal ligament",
        "anterior longitudinal ligament",
        "facet arthropathy",
        "uncovertebral joint",
        "pars interarticularis",
        "diffuse idiopathic skeletal hyperostosis",
        "osteochondral defect",
        "subchondral sclerosis",
        "labral tear",
        "meniscal tear",
        "tendinopathy",
        "tendinosis",
        "tenosynovitis",
        "enthesopathy",
        "enthesophyte",
        "syndesmophyte",
        "periosteal reaction",
        "avascular necrosis",
        "femoroacetabular impingement",
        "greater trochanteric bursitis",
        "olecranon bursitis",

        // === VASCULAR ===
        "intimal flap",
        "fibromuscular dysplasia",
        "cavernous malformation",
        "developmental venous anomaly",
        "capillary telangiectasia",
        "dural arteriovenous fistula",
        "endoleak",
        "endograft",
        "fenestrated graft",
        "inferior vena cava filter",
        "transjugular intrahepatic portosystemic shunt",

        // === BREAST IMAGING ===
        "mammography",
        "tomosynthesis",
        "architectural distortion",
        "microcalcifications",
        "macrocalcifications",
        "pleomorphic calcifications",
        "amorphous calcifications",
        "fine linear branching calcifications",
        "punctate calcifications",
        "dystrophic calcifications",
        "eggshell calcifications",
        "phyllodes tumor",
        "intraductal papilloma",
        "ductal carcinoma in situ",
        "invasive ductal carcinoma",
        "invasive lobular carcinoma",

        // === COMMONLY MISSPELLED (highest published error rates) ===
        "ophthalmology",
        "pruritus",
        "sagittal",
        "hemorrhage",
        "diarrhea",
        "abscess",
        "curettage",
        "hemorrhoid",
        "eczema",
        "syncope",
        "syphilis",
        "epididymitis",
        "gonorrhea",
        "asphyxia",
        "auscultation",

        // === SUFFIX CONFUSION TERMS ===
        "meningocele",
        "meningomyelocele",
        "encephalocele",
        "cystocele",
        "rectocele",
        "varicocele",
        "hydrocele",
        "spermatocele",
        "omphalocele",
        "gastroschisis",
        "leukopenia",
        "lymphopenia",
        "pancytopenia",
        "nephrolithiasis",
        "urolithiasis",

        // === THORACIC (Fleischner Society) ===
        "consolidation",
        "emphysema",
        "honeycombing",
        "interlobular septal thickening",
        "pneumatocele",
        "air trapping",
        "traction bronchiectasis",
        "reticulation",
        "miliary pattern",
        "pulmonary alveolar proteinosis",
        "nonspecific interstitial pneumonia",
        "usual interstitial pneumonia",
        "eosinophilic pneumonia",
        "lipoid pneumonia",
        "radiation pneumonitis",
        "pulmonary edema",
        "pulmonary hemorrhage",
        "pulmonary infarction",
        "pulmonary sequestration",
        "bronchogenic cyst",
        "pericardial effusion",
        "pleural effusion",
        "pneumopericardium",
        "mediastinal lymphadenopathy",

        // === TIER 3 ANATOMY (common but frequently mistranscribed) ===
        "adnexa",
        "antrum",
        "bifurcation",
        "calyces",
        "calvarium",
        "cerebellum",
        "cerebrum",
        "choroid",
        "clivus",
        "cochlea",
        "condyle",
        "conus",
        "cortex",
        "cuneus",
        "dens",
        "fascia",
        "fissure",
        "fossa",
        "fundus",
        "hilum",
        "labrum",
        "lamina",
        "lumen",
        "manubrium",
        "medulla",
        "meniscus",
        "navicular",
        "olecranon",
        "omentum",
        "parenchyma",
        "patella",
        "peduncle",
        "pedicle",
        "perineum",
        "phalanges",
        "pisiform",
        "plexus",
        "plicae",
        "psoas",
        "pulvinar",
        "pylorus",
        "ramus",
        "sulci",
        "tentorium",
        "thorax",
        "thymus",
        "tubercle",
        "uncus",
        "uvula",
        "vermis",
        "vestibule",
        "viscera",

        // === TIER 3 PATHOLOGY (common terms) ===
        "calcification",
        "carcinoma",
        "contusion",
        "desiccation",
        "edema",
        "embolus",
        "erosion",
        "exudate",
        "fibrosis",
        "fistula",
        "fracture",
        "granuloma",
        "hernia",
        "hyperemia",
        "infarct",
        "infiltrate",
        "laceration",
        "lesion",
        "malignancy",
        "necrosis",
        "nodule",
        "obstruction",
        "occlusion",
        "opacity",
        "perforation",
        "plaque",
        "sclerosis",
        "stricture",
        "ulceration",
        "varices",

        // === POSITIONING/MEASUREMENT ===
        "anteroposterior",
        "posteroanterior",
        "craniocaudad",
        "cephalocaudad",
        "superoinferior",
        "mediolateral",
        "lateromedial",
        "decubitus",
        "parasagittal",
        "paracoronal",
        "centimeters",
        "millimeters",
        "Hounsfield units",
        "craniocaudal dimension",

        // === CLASSIFICATION SYSTEMS ===
        "Gleason",
        "Fisher",
        "Hunt-Hess",
        "OPLL",
        "DISH",
        "IPMN",
        "DCIS",
        "TIPS",
        "ERCP",
    };
}
